### ISSUE TITLE
Refactor drivetrain default command and test drivetrain (11/8/23)

### ISSUE THREAD

**Issue by cshilling2000** [957SWARM/957-Bunny-Bots-23#32]
- [x] Encapsulate the code used for the drivetrain default command into a separate command class.
- [x] Correctly set swerve offsets (when zeroed, all modules should be 90 degrees off)
- [x] Ensure the swerve drive functions correctly

**Comment by tandej** [comment]
Remind me @cshilling2000, what was your issue with software module offsets?

**Comment by cshilling2000** [comment]
Nothing in particular, just how Rev likes to handle things in the Spark Max application and that it makes it a bit easier on Electrical. It also means code changes may not need to occur when swapping a module. Not opposed to software offsets, just that implementation needs to be logical.

**Comment by cshilling2000** [comment]
I would have a separate SwerveModuleOffsets constant class for clarity and mark the last time it was updated with a comment if software offsets are the way we want to go.
