### ISSUE TITLE
Ball shooter current sensing

### ISSUE THREAD

**Issue by cshilling2000** [957SWARM/957-Bunny-Bots-23#37]
Implement object ejection detection by tracking current on the shooter motor.

- Use the ExponentialMovingAverage class to perform signal filtering
- There should be a function within the subsystem to check if the value in the value in the average is above a threshold (threshold should be supplied by parameter to function), return a boolean
- Maintain the moving average by calling calculate() in the periodic function of the subsystem.
- Spark Max motor controllers have a getOutput() function.
- How can we minimize occurrences of detecting the same ball twice?

**Comment by tandej** [comment]
Use a different method, SparkMax output current or something. GetOutput is voltage which doesn't directly apply here
