### ISSUE TITLE
Driver UI

### ISSUE THREAD

**Issue by cshilling2000** [957SWARM/957-Bunny-Bots-23#39]
Develop the Driver UI for Bunny Bots 2023.

- [x] Round 1 research complete.
- [x] Round 1 front end complete.
- [x] Round 1 back end complete.
- [x] Round 1 feedback received.
- [x] Round 2 research complete.
- [x] Round 2 front end complete.
- [x] Round 2 back end complete.
- [x] Round 2 feedback received.
- [x] Data being sent to back end code and back end is updating front end.

For future rounds, a new issue will be opened.

**Comment by thePand251** [comment]
Due to time constraints, all work on UI is complete and will now just be debugging and testing existing code.
